version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./deployment/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80

  app:
    build:
      context: .
      dockerfile: ./deployment/app/Dockerfile
    environment:
      DATABASE_URL: postgres://default_postgres_user:default_postgres_password@db
      REDIS_URL: redis://redis:6379/1
      LANG: en_US.UTF-8
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: enabled
      RAILS_SERVE_STATIC_FILES: enabled
      SECRET_KEY_BASE: default_secret_key_base
    depends_on:
      - db
      - redis

  db:
    image: postgres:11
    environment:
      POSTGRES_DB: ars_production
      POSTGRES_USER: default_postgres_user
      POSTGRES_PASSWORD: default_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  postgres_data: {}
