export const ATTENDANCE = 'ATTENDANCE';
export const INTERACTIVE_SESSION = 'INTERACTIVE_SESSION';
export const MULTIPLE_CHOICE_QUESTION = 'MULTIPLE_CHOICE_QUESTION';
export const POLL = 'POLL';
export const QUESTION = 'QUESTION';
export const SINGLE_CHOICE_QUESTION = 'SINGLE_CHOICE_QUESTION';
